name = "medlinkva"
compatibility_date = "2026-09-03"
pages_build_output_dir = "dist"

[vars]
VITE_SANITY_PROJECT_ID = "dlfas4qz"
VITE_SANITY_DATASET = "production"
VITE_SANITY_API_VERSION = "2026-09-03"
SANITY_PROJECT_ID = "dlfas4qz"
SANITY_DATASET = "production"

BREVO_NEWSLETTER_LIST_ID = "13"
BREVO_CONTACT_LIST_ID = "14"
BREVO_CONSULTATION_LIST_ID = "15"

BREVO_NOTIFICATION_FROM_NAME = "MedLink VA Website"
BREVO_NOTIFICATION_TO_EMAIL = "info@medlinkva.com"
BREVO_NOTIFICATION_FROM_EMAIL = "info@medlinkva.com"
