import JSZip from "jszip";

export const maxImportedRecipients = 100;
export type SpreadsheetData = { fileName: string; worksheet?: string; rows: string[][]; rowsRead: number };
export type RecipientImportPreview = { fileName: string; worksheet?: string; rowsRead: number; validNames: string[]; blankRows: number; duplicates: string[]; issues: string[] };

function normalizedHeader(value: unknown) { return String(value ?? "").trim().toLowerCase().replace(/\s+/g, " "); }
function normalizedName(value: unknown) { return String(value ?? "").trim().replace(/\s+/g, " "); }
function xmlChildren(element: Element, name: string) { return [...element.getElementsByTagName("*")].filter((child) => child.localName === name); }
function parseCsvRows(value: string) { const rows: string[][] = []; let row: string[] = []; let cell = ""; let quoted = false; for (let index = 0; index < value.length; index += 1) { const character = value[index]; const next = value[index + 1]; if (character === '"' && quoted && next === '"') { cell += '"'; index += 1; } else if (character === '"') quoted = !quoted; else if (character === "," && !quoted) { row.push(cell); cell = ""; } else if ((character === "\n" || character === "\r") && !quoted) { if (character === "\r" && next === "\n") index += 1; row.push(cell); rows.push(row); row = []; cell = ""; } else cell += character; } if (cell || row.length) { row.push(cell); rows.push(row); } while (rows.length && !rows[rows.length - 1].some((item) => item.trim())) rows.pop(); return rows; }
async function parseXlsxRows(file: File) { const zip = await JSZip.loadAsync(await file.arrayBuffer()); const workbook = new DOMParser().parseFromString(await zip.file("xl/workbook.xml")!.async("string"), "application/xml"); const firstSheet = xmlChildren(workbook.documentElement, "sheet")[0]; if (!firstSheet) throw new Error("The workbook has no worksheets."); const worksheetName = firstSheet.getAttribute("name") ?? "Sheet1"; const relationshipId = firstSheet.getAttribute("r:id"); const relationshipsFile = zip.file("xl/_rels/workbook.xml.rels"); const relationships = relationshipsFile ? new DOMParser().parseFromString(await relationshipsFile.async("string"), "application/xml") : null; const relationship = relationships && xmlChildren(relationships.documentElement, "Relationship").find((item) => item.getAttribute("Id") === relationshipId); const target = relationship?.getAttribute("Target") ?? `worksheets/${worksheetName}.xml`; const worksheetPath = target.startsWith("/") ? target.slice(1) : target.startsWith("xl/") ? target : `xl/${target.replace(/^\.\//, "")}`; const worksheetFile = zip.file(worksheetPath); if (!worksheetFile) throw new Error("The first worksheet could not be read."); const sharedStringsFile = zip.file("xl/sharedStrings.xml"); const sharedStrings = sharedStringsFile ? xmlChildren(new DOMParser().parseFromString(await sharedStringsFile.async("string"), "application/xml").documentElement, "si").map((item) => xmlChildren(item, "t").map((text) => text.textContent ?? "").join("")) : []; const document = new DOMParser().parseFromString(await worksheetFile.async("string"), "application/xml"); const rows = xmlChildren(document.documentElement, "row").map((row) => { const values: string[] = []; for (const cell of xmlChildren(row, "c")) { const reference = cell.getAttribute("r") ?? "A1"; const column = [...reference].findIndex((character) => /\d/.test(character)); const index = [...reference.slice(0, column)].reduce((total, character) => total * 26 + character.charCodeAt(0) - 64, 0) - 1; const value = xmlChildren(cell, "v")[0]?.textContent ?? xmlChildren(cell, "t")[0]?.textContent ?? ""; values[index] = cell.getAttribute("t") === "s" ? (sharedStrings[Number(value)] ?? "") : value; } return values.map((value) => value ?? ""); }); return { worksheetName, rows }; }
export async function parseSpreadsheetRows(file: File): Promise<SpreadsheetData> { if (file.size > 5 * 1024 * 1024) throw new Error("This file is larger than the 5 MB upload limit."); const extension = file.name.toLowerCase().split(".").pop(); if (extension !== "csv" && extension !== "xlsx") throw new Error("Unsupported file type. Upload an Excel (.xlsx) or CSV (.csv) file."); const parsed = extension === "csv" ? { rows: parseCsvRows(await file.text()), worksheetName: undefined } : await parseXlsxRows(file); if (!parsed.rows.length) throw new Error("The uploaded file is empty."); return { fileName: file.name, worksheet: parsed.worksheetName, rows: parsed.rows, rowsRead: parsed.rows.length - 1 }; }
export async function parseRecipientFile(file: File): Promise<RecipientImportPreview> { const parsed = await parseSpreadsheetRows(file); const headers = parsed.rows[0].map(normalizedHeader); const column = headers.findIndex((header) => header === "recipient name") >= 0 ? headers.findIndex((header) => header === "recipient name") : headers.findIndex((header) => header === "recipient" || header === "name"); if (column < 0) throw new Error("No 'Recipient Name' column was found. Please use the MedLink VA recipient template."); const seen = new Map<string, string>(); const validNames: string[] = []; const duplicates: string[] = []; const issues: string[] = []; let blankRows = 0; for (const [index, row] of parsed.rows.slice(1).entries()) { const rowNumber = index + 2; const name = normalizedName(row[column]); if (!name) { blankRows += 1; if (issues.length < 20) issues.push(`Row ${rowNumber} — blank recipient name`); continue; } const key = name.toLowerCase(); if (seen.has(key)) { duplicates.push(seen.get(key)!); if (issues.length < 20) issues.push(`Row ${rowNumber} — duplicate: ${seen.get(key)}`); continue; } seen.set(key, name); validNames.push(name); } if (!validNames.length) throw new Error("No valid recipient names were found beneath the recipient column."); if (validNames.length > maxImportedRecipients) throw new Error(`This file contains ${validNames.length} valid recipients. The maximum cohort size is ${maxImportedRecipients}.`); return { fileName: parsed.fileName, worksheet: parsed.worksheet, rowsRead: parsed.rowsRead, validNames, blankRows, duplicates: [...new Set(duplicates)], issues }; }
