import { useEffect } from "react";
import { Link, useParams } from "react-router-dom";
import { Seo } from "../components/Seo";
import { HomeSection } from "../components/home/HomeSection";
import { SectionHeading } from "../components/home/SectionHeading";
import { PageCta } from "../components/shared/PageCta";
import { PageHero } from "../components/shared/PageHero";
import { InfoCard } from "../components/shared/InfoCard";
import { TestimonialSection } from "../components/shared/TestimonialSection";
import { useCmsBundle } from "../lib/cms/SiteContentProvider";
import { resolveResourcesContent, toPlainText } from "../lib/cms/siteContent";
import { sanityImageSrc } from "../lib/sanity/image";
import { clientAssets } from "../lib/assets";
import { trackHireMvaCtaClick, trackImpactCtaClick, trackResourceOpen } from "../lib/analytics";

const roles = [
  ["Virtual Medical Receptionist", "Support front-desk communication, appointment requests, and organized patient-facing workflows."],
  ["Medical Administrative Assistant", "Help keep calendars, records, referrals, and administrative follow-through organized."],
  ["Patient Coordinator", "Support non-clinical coordination, reminders, follow-up, and communication workflows."],
  ["Medical Scribe", "Provide documentation support within the role scope and workflow defined by the practice."],
  ["Insurance Verification Assistant", "Assist with insurance-related administrative checks, information gathering, and follow-up."],
  ["Billing Support Assistant", "Support organized billing administration and workflow coordination without providing clinical care."],
  ["Remote Patient Monitoring Support", "Help organize monitoring records, reminders, and workflow alerts for practice teams."],
  ["EHR / Workflow Support Assistant", "Support responsible administrative use of EHR and practice workflow systems."],
] as const;

const preparation = [
  ["Healthcare foundations", "Build context for how healthcare teams, patients, and practice operations work together."],
  ["Administrative workflows", "Practice scheduling, coordination, documentation support, referrals, and organized follow-through."],
  ["Clinical support awareness", "Understand appropriate boundaries for non-licensed administrative and support roles."],
  ["Privacy-conscious working", "Learn responsible data handling, confidentiality, secure communication, and access habits."],
  ["Practical simulations", "Apply concepts through workflow exercises that reflect common remote healthcare support tasks."],
  ["Professional readiness", "Develop communication, reliability, collaboration, and career preparation skills."],
] as const;

function SmartCta({ label, to, location, impact = false }: { label: string; to: string; location: string; impact?: boolean }) {
  return <Link to={to} className="btn-primary" onClick={() => impact ? trackImpactCtaClick(label, to, location) : trackHireMvaCtaClick(label, to, location)}>{label}</Link>;
}

function Metrics({ heading = "Our Impact in Numbers" }: { heading?: string }) {
  const metrics = useCmsBundle()?.aboutContent?.metrics?.filter((metric) => metric.active !== false && metric.label && metric.value) ?? [];
  return <HomeSection className="bg-brand-muted/50 py-16 sm:py-20"><SectionHeading eyebrow="Measured progress" title={heading} description="A snapshot of the people trained, opportunities created, and healthcare support enabled through MedLink VA." /><div className="mt-8 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{metrics.length ? metrics.map((metric) => <div key={`${metric.label}-${metric.value}`} className="surface-card p-6"><p className="text-4xl font-bold text-brand-accent">{metric.value}{metric.suffix ?? ""}</p><h3 className="mt-3 text-lg font-semibold text-brand-navy">{metric.label}</h3>{metric.description ? <p className="mt-2 text-sm leading-6 text-brand-charcoal/75">{metric.description}</p> : null}</div>) : <div className="surface-card p-6 sm:col-span-2"><p className="text-sm leading-7 text-brand-charcoal/75">Verified impact metrics will appear here as they are maintained in the CMS.</p></div>}</div><div className="mt-8"><SmartCta label="Explore Our Impact" to="/impact" location="impact_metrics" impact /></div></HomeSection>;
}

function ModelSection() {
  const steps = [["Train", "Practical Virtual Medical Assistant education"], ["Prepare", "Healthcare workflows, simulations, and career readiness"], ["Connect", "Placement support and employer connections"], ["Support", "Ongoing learning, development, and professional support"]] as const;
  return <HomeSection className="bg-white py-16 sm:py-20"><SectionHeading eyebrow="How MedLink VA creates impact" title="From learning to opportunity" description="A connected pathway for aspiring Virtual Medical Assistants and healthcare practices." /><div className="mt-8 grid gap-5 md:grid-cols-2 xl:grid-cols-4">{steps.map(([title, description], index) => <InfoCard key={title} eyebrow={`0${index + 1}`} title={title} description={description} />)}</div></HomeSection>;
}

export function HireAnMvaPage() {
  return <article><Seo title="Hire a Virtual Medical Assistant | MedLink VA" description="Connect with trained Virtual Medical Assistants prepared to support healthcare administrative workflows and remote practice operations." /><PageHero eyebrow="For Healthcare Practices" title="Hire a Trained Virtual Medical Assistant" description="MedLink VA helps healthcare practices connect with trained Virtual Medical Assistants prepared to support administrative workflows, patient coordination, scheduling, documentation, insurance-related tasks, and remote practice operations." actions={[{ label: "Request an MVA", to: "/book-consultation", variant: "primary" }, { label: "How We Prepare MVAs", to: "/how-we-prepare-mvas", variant: "secondary" }]} image={{ src: clientAssets.teamPhoto, alt: "MedLink VA team members collaborating", caption: "Matching based on role needs and candidate preparation." }} /><HomeSection className="bg-brand-background py-16 sm:py-20"><SectionHeading eyebrow="Support roles" title="What an MVA can help with" description="Role scope should be agreed with the practice and remains focused on administrative and support work." /><div className="mt-8 grid gap-5 md:grid-cols-2 xl:grid-cols-4">{roles.map(([title, description]) => <InfoCard key={title} title={title} description={description} footer={<Link to="/book-consultation" className="font-semibold text-brand-accent hover:text-brand-navy" onClick={() => trackHireMvaCtaClick("Request support", "/book-consultation", title)}>Request support →</Link>} />)}</div></HomeSection><HomeSection className="bg-white py-16 sm:py-20"><SectionHeading eyebrow="How hiring works" title="A clear path to the right conversation" description="A simple process keeps expectations clear for practices and candidates." /><div className="mt-8 grid gap-5 md:grid-cols-2 xl:grid-cols-5">{["Tell us what support you need", "We identify suitable candidates", "You review the match", "Onboarding begins", "Ongoing support continues"].map((step, index) => <InfoCard key={step} eyebrow={`0${index + 1}`} title={step} description="Matching is based on role needs and candidate preparation." />)}</div></HomeSection><TestimonialSection audiences={["client", "practice"]} /><PageCta title="Ready to discuss your practice needs?" description="Share the workflow or support role you are considering and we can discuss an appropriate next step." primaryAction={{ label: "Request an MVA", to: "/book-consultation" }} secondaryAction={{ label: "Explore Impact", to: "/impact" }} /></article>;
}

export function ImpactPage() {
  return <article><Seo title="Our Impact | MedLink VA" description="See how MedLink VA combines practical training, career preparation, placement support, and healthcare workforce connections." /><PageHero eyebrow="Our Impact" title="Creating Skills. Creating Opportunities. Supporting Healthcare." description="MedLink VA combines practical training, career preparation, placement support, and healthcare workforce connections to create opportunities for aspiring Virtual Medical Assistants and support modern healthcare practices." actions={[{ label: "Explore Training", to: "/classes", variant: "primary" }, { label: "Hire an MVA", to: "/hire-an-mva", variant: "secondary" }]} image={{ src: clientAssets.supportPhoto, alt: "Virtual Medical Assistant working remotely" }} /><Metrics /><ModelSection /><HomeSection className="bg-brand-background py-16 sm:py-20"><SectionHeading eyebrow="Stories and updates" title="Impact grows through people" description="Explore verified trainee, graduate, client, and practice stories as they become available in the CMS." /><div className="mt-8 grid gap-5 md:grid-cols-2"><InfoCard title="Graduate stories" description="Published stories can show learning journeys and verified outcomes without overstating results." footer={<Link to="/resources" className="font-semibold text-brand-accent">Browse Resources →</Link>} /><InfoCard title="Work placement highlights" description="Placement and employer updates can be added here when approved for publication." footer={<Link to="/contact" className="font-semibold text-brand-accent">Share an update →</Link>} /></div></HomeSection><TestimonialSection audiences={["trainee", "client", "practice"]} /><PageCta title="Be part of the pathway" description="Whether you are preparing for a career or strengthening a healthcare practice, start with the route that fits your goal." primaryAction={{ label: "Explore Training", to: "/classes" }} secondaryAction={{ label: "Hire an MVA", to: "/hire-an-mva" }} /></article>;
}

export function PrepareMvasPage() {
  return <article><Seo title="How We Prepare Virtual Medical Assistants | MedLink VA" description="Learn how MedLink VA prepares Virtual Medical Assistants through practical healthcare workflows, responsible data handling, simulation, and career readiness." /><PageHero eyebrow="Training approach" title="How We Prepare Virtual Medical Assistants" description="Our training and preparation approach focuses on practical healthcare workflows, professional communication, responsible data handling, simulation, and career readiness." actions={[{ label: "Hire a Prepared MVA", to: "/hire-an-mva", variant: "primary" }, { label: "Explore Training", to: "/classes", variant: "secondary" }]} /><HomeSection className="bg-brand-background py-16 sm:py-20"><SectionHeading eyebrow="Preparation areas" title="Skills connected to real workflows" description="Preparation connects healthcare context, workflow practice, and professional readiness." /><div className="mt-8 grid gap-5 md:grid-cols-2 xl:grid-cols-3">{preparation.map(([title, description]) => <InfoCard key={title} title={title} description={description} />)}</div></HomeSection><HomeSection className="bg-white py-16 sm:py-20"><SectionHeading eyebrow="Learning in context" title="Preparation supports responsible remote work" description="Training can help learners understand their role, communicate professionally, and contribute to organized healthcare administration while respecting client-defined processes." /><div className="mt-8 grid gap-5 md:grid-cols-3"><InfoCard title="Practice" description="Work through scenarios and workflow exercises." /><InfoCard title="Reflect" description="Build awareness of boundaries, privacy, and communication." /><InfoCard title="Prepare" description="Connect learning with career readiness and next steps." /></div></HomeSection><PageCta title="See the training pathway" description="Explore current programmes, upcoming classes, and learning options." primaryAction={{ label: "Explore Training", to: "/classes" }} secondaryAction={{ label: "Explore Impact", to: "/impact" }} /></article>;
}

export function PrivacyCompliancePage() {
  const topics = [["Why healthcare privacy matters", "Patient information deserves careful, respectful handling in every workflow."], ["HIPAA awareness", "Understand why HIPAA awareness matters for people supporting healthcare teams; this page is educational and does not claim compliance."], ["Confidentiality responsibilities", "Follow client instructions, limit access to what is needed, and raise questions when a workflow is unclear."], ["Secure communication", "Use approved channels and avoid moving patient information into unapproved tools or personal accounts."], ["What MVAs should never do", "Do not provide licensed clinical care, make clinical decisions, share credentials, or disclose patient information outside an authorized workflow."], ["Client responsibilities", "Practices define systems, access, policies, supervision, and the operational requirements for their own environment."]] as const;
  return <article><Seo title="Healthcare Privacy & Compliance Education | MedLink VA" description="Educational guidance on HIPAA awareness, confidentiality, responsible data handling, and secure remote healthcare support practices." /><PageHero eyebrow="Privacy-conscious practice" title="Healthcare Privacy & Compliance Education" description="MedLink VA promotes HIPAA awareness, privacy-conscious workflows, responsible data handling, confidentiality, and secure remote work practices." actions={[{ label: "Explore Training", to: "/classes", variant: "primary" }, { label: "Contact MedLink VA", to: "/contact", variant: "secondary" }]} /><HomeSection className="bg-brand-background py-16 sm:py-20"><SectionHeading eyebrow="Important principles" title="Good habits protect people and practices" description="These educational principles support thoughtful remote healthcare work." /><div className="mt-8 grid gap-5 md:grid-cols-2 xl:grid-cols-3">{topics.map(([title, description]) => <InfoCard key={title} title={title} description={description} />)}</div></HomeSection><HomeSection className="bg-white py-16 sm:py-20"><div className="surface-card border-brand-accent/30 bg-brand-sky/10 p-6 sm:p-8"><h2 className="heading-section">Important disclaimer</h2><p className="mt-4 max-w-3xl text-base leading-8 text-brand-charcoal/80">This page provides general educational information. It does not constitute legal advice, a certification, or a claim that MedLink VA, its trainees, clients, or systems are HIPAA compliant. Each healthcare practice is responsible for its own legal, privacy, security, access, and vendor requirements.</p></div></HomeSection><PageCta title="Discuss responsible support workflows" description="Talk with MedLink VA about training or administrative support needs and the requirements your practice needs to define." primaryAction={{ label: "Book a Consultation", to: "/book-consultation" }} secondaryAction={{ label: "Hire an MVA", to: "/hire-an-mva" }} /></article>;
}

export function ResourceDetailPage() {
  const { slug } = useParams();
  const bundle = useCmsBundle();
  const resources = resolveResourcesContent(bundle).records;
  const post = resources.find((record) => record.slug?.current === slug);
  useEffect(() => { if (post) trackResourceOpen(slug ?? "", post.title); }, [post, slug]);
  if (!post) return <article><Seo title="Resource Not Found | MedLink VA" robots="noindex,follow" /><PageHero eyebrow="Resources" title="This resource is not available" description="The resource may have moved or may not yet be published." actions={[{ label: "Browse Resources", to: "/resources", variant: "primary" }]} /></article>;
  const body = post.body?.length ? post.body : [];
  const audience = `${post.category} ${post.resourceType ?? ""}`.toLowerCase();
  const cta = audience.includes("career") || audience.includes("training") || audience.includes("vma") ? { label: "Explore Training", to: "/classes" } : audience.includes("client") || audience.includes("practice") || audience.includes("healthcare") ? { label: "Hire an MVA", to: "/hire-an-mva" } : { label: "Contact MedLink VA", to: "/contact" };
  return <article><Seo title={post.seoTitle || post.title} description={post.seoDescription || post.excerpt} robots="index,follow" image={post.coverImage ? sanityImageSrc(post.coverImage, { width: 1200, height: 675 }) ?? undefined : undefined} /><PageHero eyebrow={post.category} title={post.title} description={post.excerpt} actions={[{ label: cta.label, to: cta.to, variant: "primary" }, { label: "Back to Resources", to: "/resources", variant: "secondary" }]} image={post.coverImage ? { src: sanityImageSrc(post.coverImage, { width: 1200, height: 675 }) ?? clientAssets.hero, alt: post.coverImageAlt || post.title } : undefined} /><HomeSection className="bg-white py-16 sm:py-20"><div className="mx-auto max-w-3xl"><div className="flex flex-wrap gap-3 text-sm font-semibold text-brand-accent"><span>{post.resourceType || "Resource"}</span><span>{new Intl.DateTimeFormat("en-GB", { dateStyle: "long" }).format(new Date(post.publishedAt))}</span>{post.authorName || post.author ? <span>By {post.authorName || post.author}</span> : null}</div><div className="prose mt-8 max-w-none text-brand-charcoal">{body.length ? body.map((block) => <p key={block._key} className="mb-5 text-base leading-8">{toPlainText([block])}</p>) : <p className="text-base leading-8">{post.excerpt}</p>}</div></div></HomeSection><PageCta title="Keep exploring" description="Find more practical guidance for training, healthcare administration, and remote support workflows." primaryAction={cta} secondaryAction={{ label: "Watch Videos", to: "/videos" }} /></article>;
}
