import { Link } from "react-router-dom";
import { HomeSection } from "./HomeSection";
import { SectionHeading } from "./SectionHeading";
import { InfoCard } from "../shared/InfoCard";
import { useCmsBundle } from "../../lib/cms/SiteContentProvider";
import { trackImpactCtaClick } from "../../lib/analytics";

export function HomePathways() {
  return <HomeSection className="bg-brand-background py-16 sm:py-20"><SectionHeading eyebrow="Choose your pathway" title="Where would you like to start?" description="MedLink VA trains people, creates career opportunities, and connects healthcare practices with trained Virtual Medical Assistants." /><div className="mt-8 grid gap-5 lg:grid-cols-2"><InfoCard eyebrow="For aspiring MVAs" title="I Want to Become a Virtual Medical Assistant" description="Build practical healthcare administrative and clinical support skills, gain career preparation, and access placement support." footer={<Link to="/classes" className="btn-primary">Explore Training →</Link>} /><InfoCard eyebrow="For healthcare practices" title="I Want to Hire a Virtual Medical Assistant" description="Connect with trained Virtual Medical Assistants prepared to support healthcare workflows, patient coordination, scheduling, documentation, and administrative operations." footer={<Link to="/hire-an-mva" className="btn-primary">Hire an MVA →</Link>} /></div></HomeSection>;
}

export function HomeImpactPreview() {
  const metrics = useCmsBundle()?.aboutContent?.metrics?.filter((metric) => metric.active !== false && metric.label && metric.value) ?? [];
  return <HomeSection className="bg-white py-16 sm:py-20"><SectionHeading eyebrow="Our impact" title="The progress we are building" description="Every trainee supported, every placement opportunity created, and every healthcare team assisted represents part of the work MedLink VA is building. These figures offer a simple view of that progress so far." /><div className="mt-8 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{metrics.length ? metrics.slice(0, 4).map((metric) => <div key={`${metric.label}-${metric.value}`} className="surface-card p-6"><p className="text-4xl font-bold text-brand-accent">{metric.value}{metric.suffix ?? ""}</p><h3 className="mt-3 text-lg font-semibold text-brand-navy">{metric.label}</h3><p className="mt-2 text-sm leading-6 text-brand-charcoal/75">{metric.description}</p></div>) : <div className="surface-card p-6 sm:col-span-2"><p className="text-sm leading-7 text-brand-charcoal/75">Verified impact metrics will appear here as they are maintained in the CMS.</p></div>}</div><div className="mt-8"><Link to="/impact" className="btn-secondary" onClick={() => trackImpactCtaClick("Explore Our Impact", "/impact", "homepage_impact_preview")}>Explore Our Impact →</Link></div></HomeSection>;
}

export function HomeImpactModel() {
  const steps = [["Train", "Learners build practical Virtual Medical Assistant skills through guided training focused on real healthcare administrative work.", "/classes"], ["Prepare", "They practice communication, workflow organization, privacy-conscious working, and the professional habits needed for remote support roles.", "/how-we-prepare-mvas"], ["Connect", "Where opportunities are available, MedLink VA helps prepared learners move closer to employers and placement pathways.", "/impact#placements"], ["Support", "Learning does not stop at training. MedLink VA continues to encourage professional growth, confidence, and stronger day-to-day working habits.", "/impact#ongoing-support"]] as const;
  return <HomeSection className="bg-brand-muted/50 py-16 sm:py-20"><SectionHeading eyebrow="How MedLink VA creates impact" title="From learning to opportunity" description="MedLink VA is designed to support more than training alone. We help learners build practical skills, prepare for real healthcare workflows, connect with opportunities, and continue developing as they grow into remote healthcare support roles." /><div className="mt-8 grid gap-5 md:grid-cols-2 xl:grid-cols-4">{steps.map(([title, description, to], index) => <Link key={title} to={to} className="surface-card group flex h-full flex-col p-6 transition hover:-translate-y-1 hover:shadow-lg focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-accent motion-reduce:transform-none"><p className="text-sm font-semibold tracking-[0.3em] text-brand-accent transition-transform group-hover:translate-x-1">0{index + 1}</p><h3 className="mt-3 text-xl font-semibold text-brand-navy group-hover:underline">{title}</h3><p className="mt-3 text-sm leading-7 text-brand-charcoal/80">{description}</p><span className="mt-auto pt-6 text-sm font-semibold text-brand-accent transition-transform group-hover:translate-x-1">Learn more →</span></Link>)}</div></HomeSection>;
}

export function HomeTrustLinks() {
  return <HomeSection className="bg-white py-16 sm:py-20"><div className="grid gap-5 md:grid-cols-2"><InfoCard title="How we prepare MVAs" description="Learn about practical workflows, professional communication, responsible data handling, simulation, and career readiness." footer={<Link to="/how-we-prepare-mvas" className="font-semibold text-brand-accent">See our preparation approach →</Link>} /><InfoCard title="Privacy-conscious support" description="Explore educational guidance on HIPAA awareness, confidentiality, secure communication, and responsible data handling." footer={<Link to="/privacy-and-compliance" className="font-semibold text-brand-accent">Read privacy guidance →</Link>} /></div></HomeSection>;
}
