export type HealthcareAudience = {
  slug: string;
  title: string;
  seoTitle: string;
  eyebrow: string;
  heroImage?: string;
  workflowImage?: string;
  outcomeImage?: string;
  imageAlt?: string;
  description: string;
  context: string;
  challenges: string[];
  supportAreas: string[];
  benefits?: string[];
  workflow: string[];
  boundaries: string;
  relatedServices: string[];
  relatedResources: Array<{ title: string; slug: string }>;
  cta: { label: string; to: string };
};

const commonWorkflow = ["Patient or team request is received", "MVA collects the administrative information required by the practice", "The next step is coordinated in the approved system", "Confirmation, documentation, or a hand-off is completed", "Follow-up or escalation happens according to practice instructions"];

export const healthcareAudiences: HealthcareAudience[] = [
  { slug: "family-medicine", title: "Virtual Medical Assistant Support for Family Medicine Practices", seoTitle: "Virtual Medical Assistant Support for Family Medicine | MedLink VA", eyebrow: "Family medicine practices", description: "Support for family medicine teams coordinating varied patient needs, recurring appointments, follow-up, referrals, documentation, and day-to-day administrative communication.", context: "Family medicine practices often balance broad administrative demand across many types of patient visits and ongoing relationships. A clear remote support role can help organize the work around the care team.", challenges: ["Busy scheduling and confirmation workflows", "Follow-up and referral coordination", "Inbox, task, and documentation organization", "Insurance-related administrative work"], supportAreas: ["Appointment scheduling and confirmations", "Patient intake coordination", "Referral tracking", "Routine follow-up coordination", "Inbox and task organization", "Documentation support", "Insurance verification support", "Remote patient monitoring coordination where appropriate"], workflow: commonWorkflow, boundaries: "Support remains administrative and non-clinical. An MVA should not diagnose, prescribe, independently interpret clinical information, or make unsupervised clinical decisions.", relatedServices: ["Administrative & Front Desk Support", "Patient Care & Coordination Support", "Insurance & Billing Support"], relatedResources: [{ title: "Understanding Patient Scheduling Workflows", slug: "understanding-patient-scheduling-workflows" }, { title: "Remote Patient Monitoring Support", slug: "remote-patient-monitoring-support-administrative-role" }], cta: { label: "Request an MVA", to: "/hire-an-mva" } },
  { slug: "dental-practices", title: "Virtual Medical Assistant Support for Dental Practices", seoTitle: "Virtual Medical Assistant Support for Dental Practices | MedLink VA", eyebrow: "Dental practices", description: "Organized remote support for scheduling, confirmations, recall coordination, referrals, insurance administration, and routine dental practice workflows.", context: "Dental practices depend on consistent scheduling, recall communication, patient coordination, and administrative follow-through. Support can be shaped around the practice’s systems and defined responsibilities.", challenges: ["Keeping appointments and reminders organized", "Recall-list and follow-up coordination", "Insurance-related administrative work", "Managing routine inbox and task flow"], supportAreas: ["Scheduling and rescheduling", "Confirmations and reminders", "Patient intake coordination", "Recall-list support", "Referral coordination", "Insurance verification support", "Task and inbox organization", "Administrative follow-up and documentation support"], workflow: commonWorkflow, boundaries: "An MVA does not provide dental diagnosis, treatment planning, clinical advice, or licensed dental tasks. Clinical questions remain with the dental practice team.", relatedServices: ["Administrative & Front Desk Support", "Virtual Medical Reception", "Insurance & Billing Support"], relatedResources: [{ title: "Introduction to Insurance Verification", slug: "introduction-to-insurance-verification" }, { title: "What Healthcare Practices Should Know Before Hiring a VMA", slug: "what-healthcare-practices-should-know-before-hiring-a-vma" }], cta: { label: "Request an MVA", to: "/hire-an-mva" } },
  { slug: "mental-health", title: "Virtual Medical Assistant Support for Mental Health Providers", seoTitle: "Virtual Medical Assistant Support for Mental Health Providers | MedLink VA", eyebrow: "Mental health providers", description: "Privacy-conscious administrative support for scheduling, intake coordination, referrals, non-clinical follow-up, documentation organization, and insurance administration where appropriate.", context: "Mental health providers often need calm, consistent administrative communication and careful handling of sensitive information. A well-defined support role can help protect focus for the provider and clarity for the patient journey.", challenges: ["Sensitive scheduling and reminder workflows", "Organized intake and referral coordination", "Privacy-conscious communication", "Inbox, documentation, and insurance administration"], supportAreas: ["Scheduling and appointment reminders", "Patient intake administration", "Referral coordination", "Non-clinical follow-up", "Documentation organization", "Inbox management", "Billing and insurance administration where appropriate"], workflow: commonWorkflow, boundaries: "An MVA does not provide therapy, counseling, diagnosis, risk assessment, crisis support, or clinical decision-making. Sensitive or urgent concerns must be escalated through the provider’s defined process.", relatedServices: ["Administrative & Front Desk Support", "Patient Care & Coordination Support"], relatedResources: [{ title: "Healthcare Privacy and HIPAA Awareness for Virtual Medical Assistants", slug: "healthcare-privacy-and-hipaa-awareness-for-vmas" }, { title: "Building Professional Communication Skills", slug: "professional-communication-for-remote-healthcare-support" }], cta: { label: "Request an MVA", to: "/hire-an-mva" } },
  { slug: "specialists", title: "Virtual Medical Assistant Support for Specialist Practices", seoTitle: "Virtual Medical Assistant Support for Specialist Practices | MedLink VA", eyebrow: "Specialist practices", description: "Remote administrative support for referral intake, scheduling, prior-record coordination, patient communication, follow-up, and task tracking.", context: "Specialist practices often coordinate referrals, records, focused scheduling requirements, and follow-up across several parties. Clear task ownership helps the workflow remain visible.", challenges: ["Referral intake and prior-record coordination", "Focused scheduling requirements", "Patient communication and follow-up", "Insurance-related administration and task tracking"], supportAreas: ["Referral intake", "Scheduling and confirmations", "Prior-record coordination", "Patient communication", "Follow-up tracking", "Documentation support", "Insurance-related administration", "Task tracking"], workflow: commonWorkflow, boundaries: "An MVA supports coordination and administration only. Specialist assessment, interpretation, treatment decisions, and clinical advice remain with the qualified practice team.", relatedServices: ["Patient Care & Coordination Support", "Administrative & Front Desk Support", "Insurance & Billing Support"], relatedResources: [{ title: "Understanding Patient Scheduling Workflows", slug: "understanding-patient-scheduling-workflows" }, { title: "What Healthcare Practices Should Know Before Hiring a VMA", slug: "what-healthcare-practices-should-know-before-hiring-a-vma" }], cta: { label: "Request an MVA", to: "/hire-an-mva" } },
  { slug: "telehealth", title: "Virtual Medical Assistant Support for Telehealth Providers", seoTitle: "Virtual Medical Assistant Support for Telehealth | MedLink VA", eyebrow: "Telehealth providers", description: "Administrative support for virtual visit preparation, scheduling, reminders, patient communication, intake coordination, and remote task organization.", context: "Remote-first practices need dependable preparation, communication, and follow-through before and after virtual visits. A support role can help keep administrative steps organized.", challenges: ["Virtual visit preparation", "Reminder and confirmation consistency", "Remote intake and follow-up", "Organizing tasks across a distributed team"], supportAreas: ["Appointment scheduling", "Virtual visit preparation", "Reminder workflows", "Patient communication", "Intake administration", "Follow-up coordination", "Documentation support", "Remote task organization"], workflow: commonWorkflow, boundaries: "An MVA supports telehealth administration and coordination; they do not provide clinical telemedicine, make clinical decisions, or interpret patient information independently.", relatedServices: ["Virtual Medical Reception", "Patient Care & Coordination Support", "EHR / Practice Workflow Support Through AI Automation"], relatedResources: [{ title: "Building Professional Communication Skills", slug: "professional-communication-for-remote-healthcare-support" }, { title: "Healthcare Privacy and HIPAA Awareness for Virtual Medical Assistants", slug: "healthcare-privacy-and-hipaa-awareness-for-vmas" }], cta: { label: "Request an MVA", to: "/hire-an-mva" } },
  { slug: "healthcare-organizations", title: "Remote Administrative Support for Healthcare Organizations", seoTitle: "Remote Healthcare Administrative Support | MedLink VA", eyebrow: "Healthcare organizations", description: "A practical remote support layer for distributed scheduling, patient communication, workflow organization, documentation, task routing, and administrative operations.", context: "Healthcare organizations may coordinate work across teams, locations, and systems. Support is most effective when ownership, escalation paths, access, and communication expectations are explicit.", challenges: ["Distributed administrative coordination", "Task routing across teams", "Consistent documentation and hand-offs", "Remote operational assistance"], supportAreas: ["Scheduling coordination", "Patient communication", "Workflow organization", "Documentation support", "Task routing", "Insurance and billing support where appropriate", "Remote operational assistance"], workflow: commonWorkflow, boundaries: "The organization defines the role, access, supervision, and operational requirements. An MVA does not provide licensed clinical care or independent clinical judgment.", relatedServices: ["Administrative & Front Desk Support", "EHR / Practice Workflow Support Through AI Automation", "Remote Patient Monitoring Support"], relatedResources: [{ title: "What Healthcare Practices Should Know Before Hiring a VMA", slug: "what-healthcare-practices-should-know-before-hiring-a-vma" }, { title: "AI and Automation in Healthcare Administration", slug: "ai-and-automation-in-healthcare-administration" }], cta: { label: "Book a Consultation", to: "/book-consultation" } },
];

export function healthcareAudienceForTitle(title: string) {
  const normalized = title.toLowerCase();
  return healthcareAudiences.find((audience) => normalized.includes(audience.eyebrow.replace(" practices", "").replace(" providers", "").toLowerCase())) ?? healthcareAudiences.find((audience) => normalized.includes(audience.slug));
}

export const healthcareAudienceMedia: Record<string, { hero: string; workflow: string; outcome: string; alt: string }> = {
  "family-medicine": { hero: new URL("../assets/services/family-medicine/family-medicine-hero.png", import.meta.url).href, workflow: new URL("../assets/services/family-medicine/family-medicine-workflow.png", import.meta.url).href, outcome: new URL("../assets/services/family-medicine/family-medicine-outcomes.png", import.meta.url).href, alt: "Family medicine administrative support workflow" },
  "dental-practices": { hero: new URL("../assets/services/dental-practices/dental-practices-hero.png", import.meta.url).href, workflow: new URL("../assets/services/dental-practices/dental-practices-workflow.png", import.meta.url).href, outcome: new URL("../assets/services/dental-practices/dental-practices-outcomes.png", import.meta.url).href, alt: "Dental practice administrative support workflow" },
  "mental-health": { hero: new URL("../assets/services/mental-health/mental-health-hero.png", import.meta.url).href, workflow: new URL("../assets/services/mental-health/mental-health-workflow.png", import.meta.url).href, outcome: new URL("../assets/services/mental-health/mental-health-outcomes.png", import.meta.url).href, alt: "Mental health practice administrative support workflow" },
  specialists: { hero: new URL("../assets/services/specialists/specialists-hero.png", import.meta.url).href, workflow: new URL("../assets/services/specialists/specialists-workflow.png", import.meta.url).href, outcome: new URL("../assets/services/specialists/specialists-outcomes.png", import.meta.url).href, alt: "Specialist practice administrative support workflow" },
  telehealth: { hero: new URL("../assets/services/telehealth/telehealth-hero.png", import.meta.url).href, workflow: new URL("../assets/services/telehealth/telehealth-workflow.png", import.meta.url).href, outcome: new URL("../assets/services/telehealth/telehealth-outcomes.png", import.meta.url).href, alt: "Telehealth administrative support workflow" },
  "healthcare-organizations": { hero: new URL("../assets/services/healthcare-organizations/healthcare-organizations-hero.png", import.meta.url).href, workflow: new URL("../assets/services/healthcare-organizations/healthcare-organizations-workflow.png", import.meta.url).href, outcome: new URL("../assets/services/healthcare-organizations/healthcare-organizations-outcomes.png", import.meta.url).href, alt: "Healthcare organization administrative support workflow" },
};

export const healthcareAudienceCopy: Record<string, { intro: string; supportHeading: string; supportNarrative: string; workflowHeading: string; workflowNarrative: string; benefitHeading: string; benefitNarrative: string; boundary: string }> = {
  "family-medicine": { intro: "Family medicine practices manage a wide mix of patient needs, recurring appointments, follow-up, referrals, documentation, and everyday communication. When administrative work builds up, it can take time away from the care team. MedLink VA helps practices stay organized with trained Virtual Medical Assistants supporting clearly defined administrative workflows remotely.", supportHeading: "How a Virtual Medical Assistant can support your practice", supportNarrative: "Every practice has its own way of working, so support is built around the responsibilities, systems, communication channels, and escalation processes your team already uses. In a busy family medicine setting, that may include scheduling and confirmations, patient intake coordination, referral tracking, inbox and task organization, documentation support, insurance verification support, and—where appropriate—the administrative coordination around remote patient monitoring.", workflowHeading: "A more organized workflow", workflowNarrative: "There may be appointments to manage, patients to follow up with, referrals to track, messages to respond to, and administrative tasks moving throughout the day. With the right responsibilities clearly defined, a Virtual Medical Assistant can become an extra layer of support behind the scenes while the in-practice team focuses on higher-priority work and patient care.", benefitHeading: "Practical benefits for the team", benefitNarrative: "MedLink VA’s trained Virtual Medical Assistants can help take some pressure off your administrative team by keeping routine tasks moving, supporting clearer communication, and helping day-to-day workflows stay organized. Every practice works differently, so support is shaped around your existing priorities while clinical decisions remain with the appropriate healthcare professionals.", boundary: "Virtual Medical Assistants support agreed administrative workflows and do not replace licensed healthcare professionals. Clinical decisions, diagnosis, prescribing, and independent clinical interpretation remain with the appropriate healthcare team." },
  "dental-practices": { intro: "Dental practices depend on a steady rhythm of scheduling, reminders, recall follow-up, patient communication, and insurance-related administration. When these responsibilities pile up, they can place extra pressure on front-desk and clinical teams. MedLink VA provides trained Virtual Medical Assistants who can support agreed dental administrative workflows around the systems and procedures your practice already uses.", supportHeading: "Support that keeps routine dental workflows moving", supportNarrative: "Support may include appointment coordination, confirmations, recall communication, referral follow-up, insurance verification support, inbox organization, and routine documentation. The goal is to strengthen the workflow without disrupting how your practice serves patients or manages its day-to-day responsibilities.", workflowHeading: "A steadier front-desk rhythm", workflowNarrative: "From an appointment request through confirmation, reminders, recall follow-up, and documentation, each small step contributes to a smoother administrative experience. A clearly defined remote support role can help the in-practice team keep those steps visible and follow up consistently.", benefitHeading: "More room for the work happening in practice", benefitNarrative: "Remote administrative support may reduce pressure on the front desk, help keep patient communication consistent, and create more room for the team to focus on higher-priority work. The right starting point depends on your practice’s systems, priorities, and workflow gaps.", boundary: "Virtual Medical Assistants do not provide dental diagnosis, treatment planning, clinical advice, or licensed dental procedures. Clinical questions remain with the dental practice team." },
  "mental-health": { intro: "Mental health practices depend on thoughtful communication, consistent scheduling, organized intake, and careful administrative follow-through. Keeping those responsibilities moving smoothly can make a meaningful difference to the way the practice operates day to day. MedLink VA can support the non-clinical side of that work remotely, with particular care around privacy and clear escalation.", supportHeading: "Calm, careful support for the administrative side", supportNarrative: "A trained Virtual Medical Assistant may help with scheduling, appointment reminders, intake administration, referral coordination, inbox organization, documentation organization, and routine non-clinical follow-up. Support is shaped around the provider’s systems and instructions, with sensitive questions routed through the practice’s defined process.", workflowHeading: "Communication that respects the practice’s rhythm", workflowNarrative: "A request may move from scheduling to intake, confirmation, documentation, and follow-up. Clear ownership and careful hand-offs help the practice keep that path organized without making the support role responsible for decisions that belong to the provider.", benefitHeading: "Support that protects focus", benefitNarrative: "The aim is to help keep routine administrative work moving, support consistent communication, and give providers and practice staff more room for their professional responsibilities. Privacy-conscious working and clear escalation are part of that approach.", boundary: "Virtual Medical Assistants do not provide therapy, counseling, diagnosis, clinical assessment, crisis intervention, risk assessment, or clinical decision-making. Sensitive or urgent concerns must follow the provider’s defined process." },
  specialists: { intro: "Specialist practices often manage detailed referral pathways, records coordination, scheduling, follow-up, and patient communication. These workflows involve many small administrative steps that need to stay organized. MedLink VA helps specialist practices support those routine processes around their existing procedures.", supportHeading: "Support for referral-heavy workflows", supportNarrative: "A trained Virtual Medical Assistant can help coordinate referrals, organize prior records, manage appointments, follow up on administrative tasks, support documentation, assist with insurance administration, and keep inboxes and task lists moving. Responsibilities remain clearly defined around the practice’s systems and priorities.", workflowHeading: "Keeping the next step visible", workflowNarrative: "A referral or patient request may pass through information collection, records coordination, scheduling, confirmation, documentation, and follow-up. A support professional can help record what has happened and what remains, making hand-offs easier for the practice team.", benefitHeading: "Less friction in the administrative details", benefitNarrative: "Remote support may help improve consistency in routine coordination, reduce administrative pressure, and keep communication moving between the practice and patients. The starting point should reflect the work your team most needs to organize.", boundary: "Virtual Medical Assistants support coordination and administration only. Specialist assessment, interpretation, treatment decisions, and clinical advice remain with the qualified practice team." },
  telehealth: { intro: "Telehealth works best when the administrative side is as organized as the virtual visit itself. Scheduling, reminders, intake, patient communication, and follow-up all need to happen reliably before and after an appointment. MedLink VA can support those workflows remotely around the systems your team already uses.", supportHeading: "Administrative support for virtual care workflows", supportNarrative: "Support may include virtual appointment scheduling, reminders, intake administration, patient communication, virtual visit preparation, follow-up coordination, documentation support, and remote task organization. The role is designed to help the administrative path stay clear before and after the visit.", workflowHeading: "Ready before the visit, organized after it", workflowNarrative: "A request can move through scheduling, preparation, reminders, intake, the virtual visit hand-off, documentation, and follow-up. Clear responsibilities help the remote team know what to complete and when to involve the practice.", benefitHeading: "A more dependable remote rhythm", benefitNarrative: "A trained Virtual Medical Assistant may help keep routine communication on track, make preparation steps easier to follow, and support consistent administrative follow-through across a distributed team. Actual responsibilities should be agreed with the practice.", boundary: "Virtual Medical Assistants support telehealth administration and coordination; they do not provide clinical telemedicine, diagnosis, clinical triage, or medical decision-making." },
  "healthcare-organizations": { intro: "Healthcare organizations often manage administrative work across multiple teams, locations, systems, and communication channels. Keeping that work coordinated can be difficult when routine tasks are spread across busy staff. MedLink VA can provide an additional layer of remote administrative support within the responsibilities and systems established by the organization.", supportHeading: "Support that connects distributed work", supportNarrative: "A trained Virtual Medical Assistant may support scheduling coordination, patient communication, task routing, documentation, inbox management, workflow organization, and insurance or billing administration where appropriate. The focus is on helping teams stay organized and consistent around agreed processes.", workflowHeading: "Making ownership clearer across teams", workflowNarrative: "A request may begin in one team, move through information collection and task routing, and require confirmation, documentation, or follow-up by another. A clearly defined support role can help keep ownership and the next action visible.", benefitHeading: "Helping teams stay organized", benefitNarrative: "Remote administrative support may reduce pressure on internal teams, support clearer hand-offs, and help routine operational work keep moving. The most useful starting point is a specific workflow, defined access, and an agreed communication path.", boundary: "The organization defines the role, access, supervision, and operational requirements. An MVA does not provide licensed clinical care or independent clinical judgment." },
};
