export type HealthcareAudience = {
  slug: string;
  title: string;
  seoTitle: string;
  eyebrow: string;
  description: string;
  context: string;
  challenges: string[];
  supportAreas: string[];
  workflow: string[];
  boundaries: string;
  relatedServices: string[];
  relatedResources: Array<{ title: string; slug: string }>;
  cta: { label: string; to: string };
};

const commonWorkflow = ["Patient or team request is received", "MVA collects the administrative information required by the practice", "The next step is coordinated in the approved system", "Confirmation, documentation, or a hand-off is completed", "Follow-up or escalation happens according to practice instructions"];

export const healthcareAudiences: HealthcareAudience[] = [
  { slug: "family-medicine", title: "Virtual Medical Assistant Support for Family Medicine Practices", seoTitle: "Virtual Medical Assistant Support for Family Medicine | MedLink VA", eyebrow: "Family medicine practices", description: "Support for family medicine teams coordinating varied patient needs, recurring appointments, follow-up, referrals, documentation, and day-to-day administrative communication.", context: "Family medicine practices often balance broad administrative demand across many types of patient visits and ongoing relationships. A clear remote support role can help organize the work around the care team.", challenges: ["Busy scheduling and confirmation workflows", "Follow-up and referral coordination", "Inbox, task, and documentation organization", "Insurance-related administrative work"], supportAreas: ["Appointment scheduling and confirmations", "Patient intake coordination", "Referral tracking", "Routine follow-up coordination", "Inbox and task organization", "Documentation support", "Insurance verification support", "Remote patient monitoring coordination where appropriate"], workflow: commonWorkflow, boundaries: "Support remains administrative and non-clinical. An MVA should not diagnose, prescribe, independently interpret clinical information, or make unsupervised clinical decisions.", relatedServices: ["Administrative & Front Desk Support", "Patient Care & Coordination Support", "Insurance & Billing Support"], relatedResources: [{ title: "Understanding Patient Scheduling Workflows", slug: "understanding-patient-scheduling-workflows" }, { title: "Remote Patient Monitoring Support", slug: "remote-patient-monitoring-support-administrative-role" }], cta: { label: "Request an MVA", to: "/hire-an-mva" } },
  { slug: "dental-practices", title: "Virtual Medical Assistant Support for Dental Practices", seoTitle: "Virtual Medical Assistant Support for Dental Practices | MedLink VA", eyebrow: "Dental practices", description: "Organized remote support for scheduling, confirmations, recall coordination, referrals, insurance administration, and routine dental practice workflows.", context: "Dental practices depend on consistent scheduling, recall communication, patient coordination, and administrative follow-through. Support can be shaped around the practice’s systems and defined responsibilities.", challenges: ["Keeping appointments and reminders organized", "Recall-list and follow-up coordination", "Insurance-related administrative work", "Managing routine inbox and task flow"], supportAreas: ["Scheduling and rescheduling", "Confirmations and reminders", "Patient intake coordination", "Recall-list support", "Referral coordination", "Insurance verification support", "Task and inbox organization", "Administrative follow-up and documentation support"], workflow: commonWorkflow, boundaries: "An MVA does not provide dental diagnosis, treatment planning, clinical advice, or licensed dental tasks. Clinical questions remain with the dental practice team.", relatedServices: ["Administrative & Front Desk Support", "Virtual Medical Reception", "Insurance & Billing Support"], relatedResources: [{ title: "Introduction to Insurance Verification", slug: "introduction-to-insurance-verification" }, { title: "What Healthcare Practices Should Know Before Hiring a VMA", slug: "what-healthcare-practices-should-know-before-hiring-a-vma" }], cta: { label: "Request an MVA", to: "/hire-an-mva" } },
  { slug: "mental-health", title: "Virtual Medical Assistant Support for Mental Health Providers", seoTitle: "Virtual Medical Assistant Support for Mental Health Providers | MedLink VA", eyebrow: "Mental health providers", description: "Privacy-conscious administrative support for scheduling, intake coordination, referrals, non-clinical follow-up, documentation organization, and insurance administration where appropriate.", context: "Mental health providers often need calm, consistent administrative communication and careful handling of sensitive information. A well-defined support role can help protect focus for the provider and clarity for the patient journey.", challenges: ["Sensitive scheduling and reminder workflows", "Organized intake and referral coordination", "Privacy-conscious communication", "Inbox, documentation, and insurance administration"], supportAreas: ["Scheduling and appointment reminders", "Patient intake administration", "Referral coordination", "Non-clinical follow-up", "Documentation organization", "Inbox management", "Billing and insurance administration where appropriate"], workflow: commonWorkflow, boundaries: "An MVA does not provide therapy, counseling, diagnosis, risk assessment, crisis support, or clinical decision-making. Sensitive or urgent concerns must be escalated through the provider’s defined process.", relatedServices: ["Administrative & Front Desk Support", "Patient Care & Coordination Support"], relatedResources: [{ title: "Healthcare Privacy and HIPAA Awareness for Virtual Medical Assistants", slug: "healthcare-privacy-and-hipaa-awareness-for-vmas" }, { title: "Building Professional Communication Skills", slug: "professional-communication-for-remote-healthcare-support" }], cta: { label: "Request an MVA", to: "/hire-an-mva" } },
  { slug: "specialists", title: "Virtual Medical Assistant Support for Specialist Practices", seoTitle: "Virtual Medical Assistant Support for Specialist Practices | MedLink VA", eyebrow: "Specialist practices", description: "Remote administrative support for referral intake, scheduling, prior-record coordination, patient communication, follow-up, and task tracking.", context: "Specialist practices often coordinate referrals, records, focused scheduling requirements, and follow-up across several parties. Clear task ownership helps the workflow remain visible.", challenges: ["Referral intake and prior-record coordination", "Focused scheduling requirements", "Patient communication and follow-up", "Insurance-related administration and task tracking"], supportAreas: ["Referral intake", "Scheduling and confirmations", "Prior-record coordination", "Patient communication", "Follow-up tracking", "Documentation support", "Insurance-related administration", "Task tracking"], workflow: commonWorkflow, boundaries: "An MVA supports coordination and administration only. Specialist assessment, interpretation, treatment decisions, and clinical advice remain with the qualified practice team.", relatedServices: ["Patient Care & Coordination Support", "Administrative & Front Desk Support", "Insurance & Billing Support"], relatedResources: [{ title: "Understanding Patient Scheduling Workflows", slug: "understanding-patient-scheduling-workflows" }, { title: "What Healthcare Practices Should Know Before Hiring a VMA", slug: "what-healthcare-practices-should-know-before-hiring-a-vma" }], cta: { label: "Request an MVA", to: "/hire-an-mva" } },
  { slug: "telehealth", title: "Virtual Medical Assistant Support for Telehealth Providers", seoTitle: "Virtual Medical Assistant Support for Telehealth | MedLink VA", eyebrow: "Telehealth providers", description: "Administrative support for virtual visit preparation, scheduling, reminders, patient communication, intake coordination, and remote task organization.", context: "Remote-first practices need dependable preparation, communication, and follow-through before and after virtual visits. A support role can help keep administrative steps organized.", challenges: ["Virtual visit preparation", "Reminder and confirmation consistency", "Remote intake and follow-up", "Organizing tasks across a distributed team"], supportAreas: ["Appointment scheduling", "Virtual visit preparation", "Reminder workflows", "Patient communication", "Intake administration", "Follow-up coordination", "Documentation support", "Remote task organization"], workflow: commonWorkflow, boundaries: "An MVA supports telehealth administration and coordination; they do not provide clinical telemedicine, make clinical decisions, or interpret patient information independently.", relatedServices: ["Virtual Medical Reception", "Patient Care & Coordination Support", "EHR / Practice Workflow Support Through AI Automation"], relatedResources: [{ title: "Building Professional Communication Skills", slug: "professional-communication-for-remote-healthcare-support" }, { title: "Healthcare Privacy and HIPAA Awareness for Virtual Medical Assistants", slug: "healthcare-privacy-and-hipaa-awareness-for-vmas" }], cta: { label: "Request an MVA", to: "/hire-an-mva" } },
  { slug: "healthcare-organizations", title: "Remote Administrative Support for Healthcare Organizations", seoTitle: "Remote Healthcare Administrative Support | MedLink VA", eyebrow: "Healthcare organizations", description: "A practical remote support layer for distributed scheduling, patient communication, workflow organization, documentation, task routing, and administrative operations.", context: "Healthcare organizations may coordinate work across teams, locations, and systems. Support is most effective when ownership, escalation paths, access, and communication expectations are explicit.", challenges: ["Distributed administrative coordination", "Task routing across teams", "Consistent documentation and hand-offs", "Remote operational assistance"], supportAreas: ["Scheduling coordination", "Patient communication", "Workflow organization", "Documentation support", "Task routing", "Insurance and billing support where appropriate", "Remote operational assistance"], workflow: commonWorkflow, boundaries: "The organization defines the role, access, supervision, and operational requirements. An MVA does not provide licensed clinical care or independent clinical judgment.", relatedServices: ["Administrative & Front Desk Support", "EHR / Practice Workflow Support Through AI Automation", "Remote Patient Monitoring Support"], relatedResources: [{ title: "What Healthcare Practices Should Know Before Hiring a VMA", slug: "what-healthcare-practices-should-know-before-hiring-a-vma" }, { title: "AI and Automation in Healthcare Administration", slug: "ai-and-automation-in-healthcare-administration" }], cta: { label: "Book a Consultation", to: "/book-consultation" } },
];

export function healthcareAudienceForTitle(title: string) {
  const normalized = title.toLowerCase();
  return healthcareAudiences.find((audience) => normalized.includes(audience.eyebrow.replace(" practices", "").replace(" providers", "").toLowerCase())) ?? healthcareAudiences.find((audience) => normalized.includes(audience.slug));
}
