import familyMedicineWorkflow from "../assets/services/family-medicine/family-medicine-workflow.png";
import telehealthHero from "../assets/services/telehealth/telehealth-hero.png";
import familyMedicineOutcomes from "../assets/services/family-medicine/family-medicine-outcomes.png";
import insuranceBillingImage from "../assets/resources/insurance-billing.png";
import aiAutomationImage from "../assets/resources/ai-automation.png";
import remotePatientMonitoringImage from "../assets/resources/remote-patient-monitoring.png";

export type ServiceDetail = {
  slug: string;
  title: string;
  seoTitle: string;
  description: string;
  intro: string;
  support: string;
  responsibilities: readonly string[];
  workflow: readonly string[];
  teamBenefit: string;
  boundaries: string;
  audiences: readonly { label: string; to: string }[];
  resources: readonly { label: string; to: string }[];
  image: string;
  imageAlt: string;
};

export const serviceDetails: readonly ServiceDetail[] = [
  { slug: "administrative-front-desk", title: "Administrative & Front Desk Support for Healthcare Practices", seoTitle: "Administrative & Front Desk Support | MedLink VA", description: "Remote administrative support for scheduling, calendar coordination, routine communication, and the day-to-day work that keeps a practice organized.", intro: "A busy front desk handles far more than appointments. Calls, messages, scheduling changes, patient questions, calendars, and routine follow-up all need attention throughout the day.", support: "MedLink VA provides trained remote administrative support that can help healthcare practices stay organized without changing the systems and processes their teams already rely on.", responsibilities: ["Scheduling and calendar coordination", "Routine patient communication", "Inbox organization and appointment confirmations", "Task follow-up and administrative documentation"], workflow: ["The practice shares the responsibilities and systems involved.", "Routine requests, messages, or scheduling tasks are received.", "The MVA records information and completes the agreed administrative next step.", "Items needing practice input are routed through the defined communication channel.", "The team reviews the arrangement and adjusts responsibilities when needed."], teamBenefit: "A clear remote role can take pressure off the front desk and help the team keep routine work visible and moving.", boundaries: "Support is administrative and non-clinical. An MVA does not diagnose, prescribe, triage clinically, or make independent clinical decisions.", audiences: [{ label: "Family medicine practices", to: "/healthcare-teams/family-medicine" }, { label: "Healthcare organizations", to: "/healthcare-teams/healthcare-organizations" }], resources: [{ label: "Understanding Patient Scheduling Workflows", to: "/resources/understanding-patient-scheduling-workflows" }], image: familyMedicineWorkflow, imageAlt: "Family medicine administrative support workflow" },
  { slug: "virtual-medical-reception", title: "Virtual Medical Reception Support", seoTitle: "Virtual Medical Reception Support | MedLink VA", description: "Remote reception support for routine enquiries, message routing, appointment coordination, and a professional first point of contact.", intro: "The first interaction a patient has with a practice often happens before they walk through the door. Calls, appointment requests, messages, confirmations, and routine questions all shape that experience.", support: "MedLink VA’s Virtual Medical Assistants can provide remote reception support for agreed front-line administrative responsibilities, helping practices keep communication organized and responsive.", responsibilities: ["Responding to routine, approved enquiries", "Routing messages to the right practice contact", "Coordinating appointments and basic updates", "Supporting confirmations and reception follow-up"], workflow: ["The practice defines approved reception responsibilities and escalation routes.", "Calls, messages, or requests arrive through the agreed channel.", "The MVA responds using practice-approved information and records the interaction.", "Clinical or sensitive questions are routed to the appropriate practice team member.", "The practice reviews communication quality and any recurring questions."], teamBenefit: "A dependable virtual reception role can help the practice respond consistently while keeping clinical questions with qualified staff.", boundaries: "Virtual reception does not include clinical triage, diagnosis, medical advice, or independent interpretation of patient information.", audiences: [{ label: "Dental practices", to: "/healthcare-teams/dental-practices" }, { label: "Telehealth providers", to: "/healthcare-teams/telehealth" }], resources: [{ label: "Building Professional Communication Skills", to: "/resources/professional-communication-for-remote-healthcare-support" }], image: telehealthHero, imageAlt: "Telehealth administrative support workflow" },
  { slug: "patient-care-coordination", title: "Patient Care & Coordination Support", seoTitle: "Patient Care & Coordination Support | MedLink VA", description: "Non-clinical support for follow-up, reminders, routine communication, referrals, and coordination between patients and practice teams.", intro: "Good coordination helps patients move through the administrative side of care with fewer missed steps. Appointment follow-up, referrals, reminders, communication, and documentation often involve several people and systems.", support: "A trained Virtual Medical Assistant can help keep these non-clinical coordination tasks organized so the practice team has clearer visibility of what still needs attention.", responsibilities: ["Appointment and reminder follow-up", "Referral and intake coordination", "Routine non-clinical communication", "Documentation and task tracking"], workflow: ["The practice identifies the coordination tasks and approved information.", "A patient, referral, or follow-up item is recorded in the agreed system.", "The MVA completes the defined administrative action.", "Unanswered, sensitive, or urgent items are escalated through the practice process.", "The team reviews open tasks and next steps."], teamBenefit: "Organized follow-up can make hand-offs clearer and help the team see which routine administrative tasks still need attention.", boundaries: "This is non-clinical coordination support. An MVA does not provide care management, clinical assessment, treatment advice, or medical decisions.", audiences: [{ label: "Family medicine practices", to: "/healthcare-teams/family-medicine" }, { label: "Specialist practices", to: "/healthcare-teams/specialists" }], resources: [{ label: "Remote Patient Monitoring Support", to: "/resources/remote-patient-monitoring-support-administrative-role" }], image: familyMedicineOutcomes, imageAlt: "Family medicine team support outcome" },
  { slug: "insurance-billing", title: "Insurance & Billing Administrative Support", seoTitle: "Insurance & Billing Administrative Support | MedLink VA", description: "Administrative help with insurance information, verification tasks, documentation, authorization follow-up, and billing-related coordination.", intro: "Insurance-related administration can involve repeated verification, documentation, follow-up, and communication before a claim or billing workflow moves forward.", support: "MedLink VA can support clearly defined administrative parts of these processes, helping practices organize insurance information, verification tasks, and routine follow-up.", responsibilities: ["Insurance verification and eligibility checks", "Documentation organization", "Authorization follow-up where client-defined", "Billing administration and referral documentation"], workflow: ["The practice defines the information, systems, and responsibilities involved.", "Insurance or billing information is collected through approved channels.", "The MVA organizes records and completes the agreed administrative check.", "Items requiring payer, legal, or practice judgment are routed to the appropriate team.", "Open items and follow-up dates are recorded for review."], teamBenefit: "Consistent administrative follow-up can help reduce avoidable gaps in records and make the status of routine items easier to see.", boundaries: "MedLink VA does not provide legal, insurance, financial, coding, or clinical advice. Practice and payer decisions remain with the appropriate qualified parties.", audiences: [{ label: "Dental practices", to: "/healthcare-teams/dental-practices" }, { label: "Specialist practices", to: "/healthcare-teams/specialists" }], resources: [{ label: "Introduction to Insurance Verification", to: "/resources/introduction-to-insurance-verification" }], image: insuranceBillingImage, imageAlt: "Insurance and billing administrative resource" },
  { slug: "ehr-workflow-ai-automation", title: "EHR & Practice Workflow Support Through Responsible Automation", seoTitle: "EHR & Healthcare Workflow Automation Support | MedLink VA", description: "Responsible administrative automation for reminders, task routing, document organization, and repetitive workflow support with human review kept central.", intro: "Healthcare teams often repeat the same administrative steps across scheduling, reminders, documentation, follow-up, and task management. When those processes are clearly defined, technology can help reduce repetitive work.", support: "MedLink VA supports the use of responsible administrative automation while keeping human review, privacy, and professional judgment central.", responsibilities: ["Reminder and follow-up workflows", "Task routing and administrative workflow automation", "Document organization and data-entry support", "EHR workflow support with human review"], workflow: ["The practice identifies a repetitive administrative process.", "The team agrees the approved inputs, outputs, access, and review points.", "Automation assists with the defined administrative step.", "A person reviews the result before it is used or sent onward.", "The workflow is monitored and adjusted when practice needs change."], teamBenefit: "Thoughtful automation may give teams more time for work that needs their attention while keeping responsibility with people.", boundaries: "Automation and AI do not make clinical decisions, interpret patient information independently, diagnose, prescribe, or replace professional judgment. Privacy and access controls remain the practice’s responsibility.", audiences: [{ label: "Healthcare organizations", to: "/healthcare-teams/healthcare-organizations" }, { label: "Telehealth providers", to: "/healthcare-teams/telehealth" }], resources: [{ label: "AI and Automation in Healthcare Administration", to: "/resources/ai-and-automation-in-healthcare-administration" }], image: aiAutomationImage, imageAlt: "AI automation resource for healthcare administration" },
  { slug: "remote-patient-monitoring", title: "Remote Patient Monitoring Administrative Support", seoTitle: "Remote Patient Monitoring Administrative Support | MedLink VA", description: "Administrative support for enrollment, reminders, device coordination, documentation, and information routing around remote patient monitoring.", intro: "Remote Patient Monitoring often involves more than technology alone. Enrollment, reminders, follow-up, device coordination, documentation, and information routing all need to stay organized around the clinical team.", support: "A Virtual Medical Assistant may support these administrative workflows where responsibilities are clearly defined by the practice.", responsibilities: ["Enrollment and administrative onboarding support", "Reminder and follow-up coordination", "Device or information routing", "Record organization and task tracking"], workflow: ["The practice defines the monitoring programme and the MVA’s administrative role.", "Enrollment, reminder, or device-related information is received.", "The MVA records and routes the information through approved systems.", "Clinical readings or concerns are escalated without interpretation.", "The practice reviews outstanding administrative tasks and follow-up."], teamBenefit: "Keeping the administrative side organized can help the clinical team see what has been received, what needs routing, and what remains open.", boundaries: "An MVA does not interpret readings, diagnose, triage clinically, prescribe, or make independent clinical decisions. Clinical review remains with the appropriate healthcare professional.", audiences: [{ label: "Family medicine practices", to: "/healthcare-teams/family-medicine" }, { label: "Healthcare organizations", to: "/healthcare-teams/healthcare-organizations" }], resources: [{ label: "Remote Patient Monitoring Support", to: "/resources/remote-patient-monitoring-support-administrative-role" }], image: remotePatientMonitoringImage, imageAlt: "Remote patient monitoring administrative resource" },
];

export function getServiceDetail(slug: string) {
  return serviceDetails.find((service) => service.slug === slug);
}
