import type { PortableTextBlock, ResourcePostDocument } from "../lib/sanity/types";

type Section = { heading: string; paragraphs: string[]; bullets?: string[] };

function block(text: string, style: string = "normal", index = 0): PortableTextBlock {
  return { _key: `starter-${index}-${text.slice(0, 8)}`, _type: "block", style, children: [{ _key: `span-${index}`, _type: "span", text }] };
}

function body(sections: Section[]): PortableTextBlock[] {
  let index = 0;
  return sections.flatMap((section) => [block(section.heading, "h2", index++), ...section.paragraphs.map((paragraph) => block(paragraph, "normal", index++)), ...(section.bullets ?? []).map((bullet) => block(bullet, "normal", index++))]);
}

const shared = "This educational guide is intended to support thoughtful administrative and support work. It is not medical, legal, billing, or compliance advice, and role scope should always follow the healthcare practice’s instructions.";

export const starterResources: ResourcePostDocument[] = [
  {
    _id: "starter-vma-do",
    active: true,
    title: "What Does a Virtual Medical Assistant Do?",
    slug: { current: "what-does-a-virtual-medical-assistant-do" },
    excerpt: "An introduction to the responsibilities, workflows, boundaries, and professional expectations of a Virtual Medical Assistant.",
    category: "VMA Training",
    resourceType: "Training Resource",
    publishedAt: "2026-01-10",
    callToActionLabel: "Explore Training",
    body: body([
      { heading: "What a VMA is", paragraphs: ["A Virtual Medical Assistant supports healthcare administration remotely. The role can include organized communication, scheduling, documentation support, coordination, and workflow follow-through. The exact responsibilities depend on the practice, systems, supervision, and role description."] },
      { heading: "Common responsibilities", paragraphs: ["A VMA may help with appointment requests, reminders, inbox or task organization, referrals, records preparation, insurance-related administration, and non-clinical patient communication. These tasks support the practice without replacing licensed clinical judgment."] },
      { heading: "Communication and coordination", paragraphs: ["Clear, respectful communication is central to remote support. A VMA needs to record the next action, use approved channels, confirm what has been completed, and escalate uncertainty rather than guessing."] },
      { heading: "Documentation and boundaries", paragraphs: ["Documentation support means organizing information according to the client’s workflow. A VMA should not diagnose, prescribe, independently interpret clinical information, or perform tasks outside the authorized scope."] },
      { heading: "Why preparation matters", paragraphs: ["Practical preparation helps learners understand both the task and the context around it. Training, simulations, professional communication, privacy awareness, and career readiness create a stronger foundation for responsible support work.", shared] },
    ]),
  },
  {
    _id: "starter-hiring-guide",
    active: true,
    title: "What Healthcare Practices Should Know Before Hiring a VMA",
    slug: { current: "what-healthcare-practices-should-know-before-hiring-a-vma" },
    excerpt: "A practical guide to defining the role, workflows, communication expectations, and onboarding needs before hiring a Virtual Medical Assistant.",
    category: "Healthcare Administration",
    resourceType: "Guide",
    publishedAt: "2026-01-12",
    callToActionLabel: "Hire an MVA",
    body: body([
      { heading: "Start with the support gap", paragraphs: ["List the recurring work that is slowing the practice down or receiving inconsistent follow-through. A clear problem statement makes it easier to discuss the right support role."] },
      { heading: "Define tasks and boundaries", paragraphs: ["Separate administrative tasks from clinical decisions. Clarify what the VMA may do, what requires review, and what should always be escalated to the practice team."] },
      { heading: "Document workflows", paragraphs: ["Write down the normal path for scheduling, follow-up, referrals, documentation, and hand-offs. Even a simple checklist helps a new team member understand sequence and ownership."] },
      { heading: "Plan communication and access", paragraphs: ["Decide which channels, systems, response expectations, and access levels apply. Access should be assigned carefully and reviewed by the practice according to its own policies."] },
      { heading: "Prepare onboarding and feedback", paragraphs: ["Set an initial orientation, clear points of contact, and a regular way to review questions and workflow quality. A practical conversation about needs is more useful than assuming every practice has the same operating model.", shared] },
    ]),
  },
  {
    _id: "starter-privacy-awareness",
    active: true,
    title: "Healthcare Privacy and HIPAA Awareness for Virtual Medical Assistants",
    slug: { current: "healthcare-privacy-and-hipaa-awareness-for-vmas" },
    excerpt: "An educational overview of privacy awareness, confidentiality, responsible data handling, and why HIPAA principles matter in remote healthcare support.",
    category: "VMA Training",
    resourceType: "Training Resource",
    publishedAt: "2026-01-14",
    callToActionLabel: "Learn About Privacy & Compliance",
    body: body([
      { heading: "What privacy awareness means", paragraphs: ["Privacy-aware work means treating patient information as sensitive, using only approved systems, and following the practice’s instructions for access, communication, storage, and escalation."] },
      { heading: "Minimum necessary access", paragraphs: ["People should only access the information needed for an authorized task. A VMA should not browse unrelated records, create unnecessary copies, or send information through personal or unapproved channels."] },
      { heading: "Credentials and communication", paragraphs: ["Protect passwords, avoid sharing credentials, lock devices when away, and confirm that communication is being sent through an approved workflow. When something is unclear, pause and ask the designated contact."] },
      { heading: "Escalation and client responsibility", paragraphs: ["Privacy education helps a learner recognize risk, but each practice defines its own legal, security, access, vendor, and supervision requirements. This guide does not claim that MedLink VA, trainees, clients, or systems are automatically HIPAA compliant."] },
      { heading: "A practical habit", paragraphs: ["Before sending or saving information, ask: Is this necessary for the task? Is this the approved place? Is the recipient authorized? If the answer is uncertain, escalate rather than improvise.", shared] },
    ]),
  },
  {
    _id: "starter-scheduling",
    active: true,
    title: "Understanding Patient Scheduling Workflows",
    slug: { current: "understanding-patient-scheduling-workflows" },
    excerpt: "A practical introduction to appointment scheduling, confirmation, follow-up, rescheduling, documentation, and communication.",
    category: "Practice Workflows",
    resourceType: "Guide",
    publishedAt: "2026-01-16",
    callToActionLabel: "Explore Training",
    body: body([
      { heading: "From request to appointment", paragraphs: ["Scheduling begins with an appointment request and the information the practice requires. The support professional checks the available options within the approved system and records the outcome clearly."] },
      { heading: "Confirmation and reminders", paragraphs: ["A confirmation should communicate the agreed time and any client-approved instructions. Reminder workflows should follow the practice’s timing, channel, and documentation expectations."] },
      { heading: "Rescheduling and missed appointments", paragraphs: ["When plans change, document the request, identify the next available options, and follow the practice’s process for missed appointments. Do not invent policy or offer clinical advice."] },
      { heading: "Hand-offs and escalation", paragraphs: ["Questions about urgency, clinical suitability, exceptions, or unclear instructions belong with the designated practice team. Good scheduling support makes the hand-off visible and traceable."] },
      { heading: "A repeatable workflow", paragraphs: ["Request, collect required information, check availability, schedule, confirm, remind, document, and escalate when needed. Repetition builds reliable habits without turning the process into a substitute for clinical judgment.", shared] },
    ]),
  },
  {
    _id: "starter-insurance",
    active: true,
    title: "Introduction to Insurance Verification",
    slug: { current: "introduction-to-insurance-verification" },
    excerpt: "An introductory guide to insurance verification workflows and the administrative role of a Virtual Medical Assistant.",
    category: "Insurance & Billing",
    resourceType: "Healthcare Administration Tip",
    publishedAt: "2026-01-18",
    callToActionLabel: "Explore Healthcare Support Services",
    body: body([
      { heading: "What insurance verification is", paragraphs: ["Insurance verification is an administrative process used by a practice to gather and confirm information relevant to a patient’s coverage and the planned workflow. The exact steps depend on the practice and payer requirements."] },
      { heading: "Information and documentation", paragraphs: ["A workflow may involve collecting the information the practice requires, checking an approved source, recording the date and result, and making uncertainty visible to the appropriate team member."] },
      { heading: "Eligibility is not authorization", paragraphs: ["Coverage or eligibility information does not automatically answer every question about authorization, benefits, payment, or clinical appropriateness. A support professional should avoid presenting an administrative check as a guarantee."] },
      { heading: "When to escalate", paragraphs: ["Escalate incomplete information, conflicting results, unclear payer instructions, or questions outside the defined role. Follow the practice’s process and do not provide legal, billing, or financial advice."] },
      { heading: "Why organized records matter", paragraphs: ["Clear notes help the practice understand what was checked, when it was checked, and what still needs review. Good documentation supports continuity without overstating certainty.", shared] },
    ]),
  },
  {
    _id: "starter-family-medicine",
    active: true,
    title: "How Virtual Medical Assistants Support Family Medicine Practices",
    slug: { current: "how-vmas-support-family-medicine-practices" },
    excerpt: "Examples of how trained Virtual Medical Assistants can support busy family medicine practices with administrative coordination.",
    category: "Healthcare Administration",
    resourceType: "Guide",
    publishedAt: "2026-01-20",
    callToActionLabel: "Hire an MVA",
    body: body([
      { heading: "Front desk and scheduling", paragraphs: ["A VMA may support appointment requests, confirmations, reminders, rescheduling, and task routing according to the practice’s workflow."] },
      { heading: "Intake and follow-up coordination", paragraphs: ["Support may include organizing non-clinical intake steps, tracking follow-up requests, and documenting the next action for the appropriate team member."] },
      { heading: "Referrals and documentation support", paragraphs: ["A VMA can help organize referral-related tasks and documentation workflows when the practice defines the process, systems, and review points clearly."] },
      { heading: "Insurance and monitoring support", paragraphs: ["Insurance-related administration and remote patient monitoring coordination may be part of a support role where appropriate. These tasks require clear boundaries and must not include independent clinical interpretation."] },
      { heading: "Designing the role", paragraphs: ["The strongest starting point is a defined support gap, agreed responsibilities, approved systems, and a named practice contact for questions. A VMA supports the team; the practice retains responsibility for its care, policies, supervision, and decisions.", shared] },
    ]),
  },
  {
    _id: "starter-interview",
    active: true,
    title: "How to Prepare for Your First VMA Interview",
    slug: { current: "how-to-prepare-for-your-first-vma-interview" },
    excerpt: "Practical steps for preparing for a Virtual Medical Assistant interview and communicating your skills clearly.",
    category: "Career Development",
    resourceType: "Career Resource",
    publishedAt: "2026-01-22",
    callToActionLabel: "Explore Training",
    body: body([
      { heading: "Understand the role", paragraphs: ["Read the role description carefully and identify the workflows, communication expectations, systems, and boundaries it describes. Prepare questions for anything that remains unclear."] },
      { heading: "Prepare practical examples", paragraphs: ["Use examples that show organization, communication, follow-through, learning, and responsible handling of uncertainty. Explain what you did, how you communicated, and what you learned."] },
      { heading: "Show remote readiness", paragraphs: ["Think about your workspace, connectivity, time management, written communication, hand-offs, and how you keep track of tasks while working remotely."] },
      { heading: "Discuss privacy awareness", paragraphs: ["Be ready to explain why approved systems, careful access, confidentiality, and escalation matter in healthcare support. Avoid claiming experience or qualifications you do not have."] },
      { heading: "Follow up professionally", paragraphs: ["After an interview, send a concise follow-up, restate your interest, and clarify any agreed next steps. Preparation is not about having every answer; it is about showing how you learn and work responsibly.", shared] },
    ]),
  },
  {
    _id: "starter-communication",
    active: true,
    title: "Building Professional Communication Skills for Remote Healthcare Support",
    slug: { current: "professional-communication-for-remote-healthcare-support" },
    excerpt: "A practical guide to clear, respectful, reliable communication in remote healthcare support roles.",
    category: "Career Development",
    resourceType: "Career Resource",
    publishedAt: "2026-01-24",
    callToActionLabel: "See How We Prepare MVAs",
    body: body([
      { heading: "Clarity and tone", paragraphs: ["Professional communication is clear, respectful, and specific. State the task, current status, next action, owner, and deadline when those details are known."] },
      { heading: "Written updates and hand-offs", paragraphs: ["A useful hand-off helps another person understand what happened without repeating the entire search. Use approved formats, keep notes factual, and identify questions that still need review."] },
      { heading: "Response times and escalation", paragraphs: ["Reliability includes acknowledging work, communicating delays, and escalating when a deadline or instruction may not be met. Silence creates uncertainty for the rest of the team."] },
      { heading: "Boundaries and teamwork", paragraphs: ["Professional communication does not mean making decisions outside the role. Ask focused questions, respect confidentiality, and involve the designated practice contact when clinical or operational judgment is required."] },
      { heading: "Learning from feedback", paragraphs: ["Feedback is a practical tool. Reflect on what was unclear, update the workflow or note format, and apply the lesson to the next hand-off.", shared] },
    ]),
  },
  {
    _id: "starter-ai",
    active: true,
    title: "AI and Automation in Healthcare Administration: Where They Help and Where People Still Matter",
    slug: { current: "ai-and-automation-in-healthcare-administration" },
    excerpt: "An introduction to practical administrative automation while keeping privacy, judgment, and human oversight central.",
    category: "AI & Automation",
    resourceType: "Healthcare Administration Tip",
    publishedAt: "2026-01-26",
    callToActionLabel: "Explore Services",
    body: body([
      { heading: "Useful repetitive tasks", paragraphs: ["Automation can help organize repetitive administrative work such as reminders, task routing, document organization, and scheduling support when the workflow and tools are approved by the practice."] },
      { heading: "Keep people in the loop", paragraphs: ["Automation should support people, not silently replace review. A team member needs to understand what a workflow does, check important outputs, and know how to correct or stop it."] },
      { heading: "Privacy and approved systems", paragraphs: ["Before using a tool, confirm what information it receives, where it goes, who can access it, and whether it is approved for the intended workflow. Do not move patient information into unapproved tools."] },
      { heading: "Limits and judgment", paragraphs: ["Automation may miss context, misread information, or produce an incomplete result. Clinical interpretation, sensitive decisions, and exceptions require the appropriate human review and practice-defined escalation."] },
      { heading: "A responsible starting point", paragraphs: ["Map the current task, identify the repetitive portion, define a review point, test with safe information, and document ownership. Thoughtful automation improves consistency without removing accountability.", shared] },
    ]),
  },
  {
    _id: "starter-rpm",
    active: true,
    title: "Remote Patient Monitoring Support: Understanding the Administrative Role",
    slug: { current: "remote-patient-monitoring-support-administrative-role" },
    excerpt: "An introduction to how non-licensed support professionals may assist with coordination around remote patient monitoring workflows.",
    category: "Remote Patient Monitoring",
    resourceType: "Healthcare Administration Tip",
    publishedAt: "2026-01-28",
    callToActionLabel: "Explore Services",
    body: body([
      { heading: "What RPM support involves", paragraphs: ["Remote patient monitoring workflows can include devices, patient communication, data routing, follow-up, and documentation. A non-licensed support role may assist with coordination defined by the practice."] },
      { heading: "Administrative coordination", paragraphs: ["Support may include reminders, organizing task lists, documenting contact attempts, and routing information to the designated clinical or practice team."] },
      { heading: "Data routing and escalation", paragraphs: ["A VMA should follow the approved process for routing information and escalating alerts or uncertainty. They should not independently interpret readings, diagnose, or make treatment decisions."] },
      { heading: "Communication and boundaries", paragraphs: ["Patient-facing communication must use practice-approved language and channels. The role should be explicit about what the support professional can and cannot answer."] },
      { heading: "Designing a safe workflow", paragraphs: ["A clear workflow identifies who reviews information, what counts as an escalation, how tasks are recorded, and how follow-up is confirmed. The practice remains responsible for clinical oversight and its own procedures.", shared] },
    ]),
  },
];
